# utilisateur et groupe sous lesquels les processus s'éxecuteront
user = www-data
group = www-data

listen = 0.0.0.0:9000

# propriétaire et groupe du socket utilisé
listen.owner = www-data
listen.group = www-data

# rend le processus PHP dynamique pour s'adapter au nombre de processus
pm = dynamic
# nombre de processus enfant max
pm.max_children = 5
# nombre de processus au lancement
pm.start_servers = 2
# nombre de processus inactif min à conserver
pm.min_spare_servers = 1
# nombre de processus inactif max a conserver
pm.max_spare_servers = 3